services:
  nest:
    build:
      context: .
      dockerfile: docker/nest/Dockerfile
    container_name: nest_pdf
    env_file:
      - .env
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./app:/opt/app
